language: 'en' # for available languages see / edit messages.yml
servername: 'this server'
messageformat: '§7[§3OnlineTime§7] %message%' # See https://minecraft.gamepedia.com/Formatting_codes
saveinterval: 30 # seconds
storage: 'yaml' # to use e.g. mysql set to 'database' and configure database.properties
configversion: 1 # Never manually edit this value! It is used to migrate older configurations to the current version.
